services:
  app:
    container_name: proxiiback
    image: scaseykoh/proxii_app
    platform: linux/amd64
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
    stdin_open: true
    tty: true
  db:
    image: postgres
    restart: unless-stopped
    platform: linux/amd64
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
